---
title: "README"
author: "Xiaowen Tian"
date: "7/22/2019"
output: rmarkdown::github_document
---
# CHMIpower

<!-- badges: start -->
<!-- badges: end -->

The goal of CHMIpower is to perform power calculation for designs of Controlled Human Malaria Infection studies.

## Installation

You can install the released version of CHMIpower from https://github.com/tianxiaowen/CHMI/blob/master/CHMIpower_0.0.0.9000.tar.gz.

Please install package dependencies first.

``` r
packages <- c("survival","beeswarm","MASS","stats","graphics","grDevices")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
install.packages("pathname/CHMIpower_0.0.0.9000.tar.gz", repos = NULL, type = "source")
```

## General setup
The Weibull distribution with shape parameter $k$ and scale parameter $\lambda$ has density given by
$f(x;k,\lambda) = \frac{k}{\lambda}(\frac{x}{\lambda})^{k-1}e^{-(x/\lambda)^k}$ for $x>0$. The hazard function is given by $h(x;k,\lambda)=\frac{k}{\lambda}(\frac{x}{\lambda})^{k-1}$. In our simulation studies, time to infection for control group is modeled by $Weibull(k,\lambda_0)$. Individuals in the treament group have probability $\rho$ being fully protected and their observations are set to be censored. Time to infection for the individuals in the treatment group who don't get full protection from the vaccine will follow $Weibull(k,\lambda_1)$. Note that the shape parameter $k$ for the Weibull distribution is same for the control and treatment group. Hence the hazard ratio $\beta$ between treatment and control group is constant and has the form of $(\frac{\lambda_0}{\lambda_1})^k$.

## Example

This is a basic example which shows you how to solve a common problem:

```{r}
library(CHMIpower)
## Power calculation for t-test, Wilconxon test, log-rank test, Lachenbruch test, and likelihood ratio test for mixture models.
powercal(beta=0.2,lambda0=8,k=5,rho=0.2,N=16,ratio=3,endstudy=28,testname=c('t-test','logrank'),alpha=0.05,seed=1)
## This function visualize a simulated dataset using a boxplot and a Kaplan-Meier curve.
simexample(beta=0.2,lambda0=8,k=5,rho=0.2,N=28,ratio=3,endstudy=28,seed=1)
## Comparison of probability density function for simulated treatment and control group.
pdfsim(beta=0.2,lambda0=8,k=5,rho=0.2,endstudy=28)
## Comparison of input data to a Weibull distribution
## Maximum-likelihood fitting of input dataset to a Weibull distribution
cdfweibull(rweibull(10,3,6),lambda=8,k=5)
```



